config/routes.rb
GoalsApp::Application.routes.draw do
  root to: "users#show"
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :comments, only: [:create]
  resources :cheers, only: [:create, :index]
  get "leaderboard", to: "cheers#index"
  resources :goals do
    member do
      post "toggle_privacy"
      post "toggle_completion"
    end
  end
end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  validates :goal, :user, :presence => true

  belongs_to :goal, :inverse_of => :cheers
  belongs_to :user, :inverse_of => :cheers
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user, :commentable, :presence => true

  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  description :text
#  user_id     :integer          not null
#  completed   :boolean          default(FALSE)
#  public      :boolean          default(FALSE)
#  created_at  :datetime
#  updated_at  :datetime
#

class Goal < ActiveRecord::Base
  include Commentable
  validates :title, :user, :presence => true
  before_validation :ensure_booleans_set

  belongs_to :user, :inverse_of => :goals
  has_many :cheers, :inverse_of => :goal

  def karma
    self.cheers.count
  end

  def ensure_booleans_set
    self.completed ||= false
    if self.privacy.nil?
      self.privacy = true
    end
  end

  def toggle_completion!
    self.completed = !self.completed
    self.save!
  end

  def toggle_privacy!
    self.privacy = !self.privacy
    self.save!
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  include Commentable
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :session_token, uniqueness: true
  before_validation :ensure_session_token

  attr_reader :password

  has_many :goals, :inverse_of => :user
  has_many :submitted_comments, class_name: "Comment"
  has_many :cheers, :inverse_of => :user

  def self.find_by_credentials(auth_params)
    user = User.find_by_username(auth_params[:username])
    return user if user && user.is_password?(auth_params[:password])
    nil
  end

  def password=(plaintext)
    @password = plaintext
    self.password_digest = BCrypt::Password.create(plaintext)
  end

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  def verify_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  before_action :verify_logged_in
  MAX_CHEERS = 1

  def index
  end

  def create
    if current_user.cheers.count < MAX_CHEERS
      cheer = current_user.cheers.new(:goal_id => params[:cheer][:goal_id])
      cheer.save
    else
      flash[:errors] = "Cheers limit reached"
    end
    redirect_to user_url(Goal.find(params[:cheer][:goal_id]).user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    class_type = params[:comment][:target_class] == "User" ? User : Goal
    target = class_type.find(params[:comment][:target_id])
    @comment = target.comments.new(comment_params)
    @comment.user = current_user
    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end

    redirect_to target.class == User ? user_url(target) : user_url(target.user)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :verify_logged_in

  def create
    @goal = current_user.goals.new(goal_params)
    unless @goal.save
      flash[:errors] = @goal.errors.full_messages
    end

    redirect_to user_url(current_user)
  end

  def destroy
    @goal = current_userl.goals.find(params[:id])
    @goal.destroy if @goal
    redirect_to user_url(current_user)
  end

  def toggle_completion
    goal = current_user.goals.find(params[:id])

    if goal
      goal.toggle_completion!
      redirect_to user_url(goal.user)
    else
      flash[:errors] = ["How did you do that?! Stop it!"]
      redirect_to user_url(current_user)
    end
  end

  def toggle_privacy
    goal = Goal.find(params[:id])
    if goal
      goal.toggle_privacy!
      redirect_to user_url(goal.user)
    else
      flash[:errors] = ["How did you do that?! Stop it!"]
      redirect_to user_url(current_user)
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description, :privacy)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :verify_logged_in, only: [:destroy]
  def new
    @user = User.new
    render "new"
  end

  def create
    @user = User.find_by_credentials(auth_params)
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(auth_params)
      flash.now[:errors] = "No user found for this Username/Password combo"
      render "new"
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  private

  def auth_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_logged_in, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @goal = Goal.new
    render "show"
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def csrf_token
    "<input type=\"hidden\"
           name=\"authenticity_token\"
           value=\"#{form_authenticity_token}\" >".html_safe
  end
end

app/helpers/cheers_helper.rb
module CheersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheers/_form.html.erb
<form action="<%= cheers_url %>" method="post">
  <%= csrf_token %>

  <input type="hidden" name="cheer[goal_id]" value="<%= goal.id %>">

  <p><input type="submit" value="Cheer!" id="cheer_goal<%= goal.id %>"></p>
</form>

app/views/cheers/index.html.erb
<% sorted_goals = Goal.where(privacy: false).sort! do |g1, g2|
  karma_diff = (g2.karma <=> g1.karma)
  karma_diff.zero? ? (g1.title.downcase <=> g2.title.downcase) : karma_diff
end %>

<h1>Leaderboard</h1>

<ol>
<% sorted_goals.each do |goal| %>
  <li><%= link_to goal.title, goal_url(goal)%>, Karma: <%= goal.karma %></li>
<% end %>
</ol>

app/views/comments/_display.html.erb
<%= comment.user.username %> wrote: <br>
<%= comment.body %><br><br>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post">
  <%= csrf_token %>

  <label>Comment
  <input type="text" name="comment[body]"
         id="comment_text_<%= target.class %><%= target.id %>"></label>

  <input type="hidden" name="comment[target_class]"
  value="<%= target.class %>">

  <input type="hidden" name="comment[target_id]"
  value="<%= target.id %>">

  <p><input type="submit" value="Submit Comment"
    id="submit_comment_<%= target.class %><%= target.id %>"></p>
</form>

app/views/goals/_display.html.erb
<% comp_button_title = goal.completed ? "Uncomplete" : "Complete" %>
<% priv_button_title = goal.privacy ?  "Make Public" : "Make Private"%>

<%= goal.title %>
  <br>
  <%= goal.completed ? "Completed!" : "In Progress" %>
  <% if goal.user == current_user %>
    <%= button_to(comp_button_title, toggle_completion_goal_url(goal),
                  method: :post)%>
    <%= goal.privacy ? "Private" : "Public" %>
    <%= button_to(priv_button_title, toggle_privacy_goal_url(goal),
                  method: :post)%>
  <% end %>
<%= goal.description if goal.description %>

app/views/goals/_form.html.erb
<form action="<%= goals_url %>" method="post">
  <%= csrf_token %>

  <label for="title">Title</label>
  <input type="text" name="goal[title]" value="<%= @goal.title %>" id="title">

  <label for="description">Description</label>
  <input type="textarea" name="goal[description]"
         value="<%= @goal.description %>" id="description">

  <label for="public">Public?</label>
  <input type="checkbox" name="goal[privacy]" id="public" value="false"
  <%= "checked".html_safe if @goal.privacy %> >

  <p><input type="submit" value="Add Goal"></p>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:errors] %>
  <%= flash[:errors].to_json %>
<% end %>

<% if flash[:notice] %>
  <%= flash[:notice].to_json %>
<% end %>

<% if logged_in? %>
  Welcome, <%= current_user.username%>!
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>


<%= yield %>

</body>
</html>

app/views/shared/_user_form.html.erb
<% action = (params[:controller] == "sessions" ? session_url : users_url )%>
<% title = (params[:controller] == "sessions" ? "Sign In" : "Sign Up")%>

<form action="<%= action %>" method="POST" accept-charset="utf-8">
  <%= csrf_token %>

  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <p><input type="submit" value="<%= title %>"></p>
</form>

app/views/users/new.html.erb
<%= render "shared/user_form" %>

app/views/users/show.html.erb
<% own_page = current_user == @user%>

This is <%= @user.username %>'s homepage!
<% @user.comments.order(:created_at).each do |comment| %>
  <p><%= render "comments/display", comment: comment %></p>
<% end %>

<%= render "comments/form", target: @user %>


<h1>Goals</h1>
<% @user.goals.order(:created_at).each do |goal| %>
  <% if own_page || !goal.privacy %>
    <p><%= render "goals/display", :goal => goal %>
      Karma: <%= goal.karma %>
      <% if !own_page &&
           Cheer.where(user_id: current_user.id, goal_id: goal.id).empty? %>
        <%= render "cheers/form", :goal => goal %>
      <% end %>

    <% goal.comments.order(:created_at).each do |comment| %>
      <p><%= render "comments/display", comment: comment %></p>
    <% end %>
    <%= render "comments/form", :target => goal%></p>

  <% end %>
  --------------------------------------------------
<% end %>

<% if own_page %>
  <h2>Create a Goal</h2>
  <%= render "goals/form" %>
<% end %>